name: test_application
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter
 # BLoC
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  # Code generation for classes
  freezed: ^2.3.5
  freezed_annotation:

  # Routing
  auto_route: ^5.0.4

  # HTTP requests
  dio: ^5.2.1+1


  # Dependency Injection
  get_it: ^7.6.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  
  flutter_lints: ^2.0.0
  
flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    
  
  fonts:
    - family: SF PRO Display 
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          
    - family: Trajan Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.TTF

  

